#version: "3.9"

services:

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis

  worker:
    build:
      context: .
      dockerfile: worker/Dockerfile
    depends_on:
      - redis

    deploy:
      replicas: 3