apiVersion: apps/v1
kind: Deployment
metadata:
  name: api

spec:
  replicas: 1

  selector:
    matchLabels:
      app: api

  template:
    metadata:
      labels:
        app: api

    spec:
      containers:
        - name: api
          image: ai-batch-inference-api
          imagePullPolicy: Never

          ports:
            - containerPort: 8000

          env:
            - name: REDIS_HOST
              value: redis

---

apiVersion: v1
kind: Service
metadata:
  name: api-service

spec:
  type: NodePort

  selector:
    app: api

  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30007